# Generated by Django 2.2.6 on 2020-04-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBoy',
            fields=[
                ('delivery_boy_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
                ('lat_long', models.CharField(max_length=30)),
            ],
        ),
    ]
