# Generated by Django 2.2.6 on 2020-04-12 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='lat_long',
            new_name='la_long',
        ),
    ]
