# Generated by Django 2.2.6 on 2020-04-12 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200411_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='OTP',
            new_name='OT',
        ),
    ]
