# Generated by Django 2.2.6 on 2020-04-12 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200411_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='OT',
            new_name='OTP',
        ),
    ]
