# Generated by Django 2.2.6 on 2020-04-11 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
        ('customer','__latest__'),
        

    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Users'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Users'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
