# Generated by Django 2.2.6 on 2020-04-11 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_auto_20200411_0956'),
        ('delivery','__latest__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotedarea',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.DeliveryBoy'),
        ),
        migrations.AlterField(
            model_name='vehicle_info',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.DeliveryBoy'),
        ),
        migrations.DeleteModel(
            name='DeliveryBoy',
        ),
    ]
